import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { useStateContext } from "../../contexts/ContextProvider";

const ImprovementTips = ({ clz }) => {
  const { selectedProduct } = useStateContext();
  const navigate = useNavigate();
  const [chartData, setChartData] = useState([]);
  const backendApiUrl = process.env.REACT_APP_BACKEND_API;
  useEffect(() => {
    console.log(selectedProduct);
    if (!selectedProduct) {
      navigate("/dashboard/search");
    } else {
      fetchChartData(selectedProduct);
      console.log(selectedProduct);
    }
  }, [selectedProduct, navigate]);

  const fetchChartData = async (asin) => {
    try {
      const headers = {
        "ngrok-skip-browser-warning": "true",
      };

      const response = await axios.get(
        `${backendApiUrl}/dashboard/improvement?asin=${asin}`,
        { headers }
      );

      setChartData(response.data); // Update chart data with the fetched data
    } catch (error) {
      console.error("Error fetching chart data:", error);
    }
  };

  return (
    <>
      <div className="bg-white dark:text-gray-200 dark:bg-secondary-dark-bg flex justify-between">
        <p className="font-semibold text-xl">Improvement tips</p>
        <div className="flex items-center gap-4">
          <p className="flex items-center gap-2 text-green-400 hover:drop-shadow-xl">
            <span>Generated by LLAMA2</span>
          </p>
        </div>
      </div>

      <div className={`mt-4 space-y-4 ${clz} overflow-y-auto`}>
        {chartData.map((tip, index) => (
          <div
            key={index}
            className="bg-gray-100 dark:bg-secondary-dark-bg p-4 rounded-lg shadow"
          >
            <p className="text-md text-gray-800 dark:text-gray-200">{tip}</p>
          </div>
        ))}
      </div>
    </>
  );
};

export default ImprovementTips;
