// ImprovementTips.js
import { improvementTips } from '../../data/dummy';

const ImprovementTips = ({ clz }) => {
  return (
    <>
      <div className="bg-white dark:text-gray-200 dark:bg-secondary-dark-bg flex justify-between">
        <p className="font-semibold text-xl">Improvement tips</p>
        <div className="flex items-center gap-4">
          <p className="flex items-center gap-2 text-green-400 hover:drop-shadow-xl">
            <span>Generated by LLAMA2</span>
          </p>
        </div>
      </div>

      <div className={`mt-4 space-y-4 ${clz} overflow-y-auto`}>
        {improvementTips.map((tip, index) => (
          <div
            key={index}
            className="bg-gray-100 dark:bg-secondary-dark-bg p-4 rounded-lg shadow"
          >
            <p className="text-md text-gray-800 dark:text-gray-200">
              {tip}
            </p>
          </div>
        ))}
      </div>
    </>
  );
};

export default ImprovementTips;
